name: Release to GHCR

defaults:
  run:
    shell: bash

env:
  TAG_NAME: ghcr.io/indubitable/cronch
  TAG_NAME_EXTRA: ghcr.io/indubitable/cronch-extra

on:
  workflow_dispatch:
    inputs:
      target_platforms:
        description: Target platform(s)
        required: true
        type: choice
        options:
          - linux/amd64,linux/arm64,linux/arm/v7
          - linux/amd64
          - linux/arm64
          - linux/arm/v7
        default: 'linux/amd64,linux/arm64,linux/arm/v7'
      tagged_version:
        description: Tagged and compiled version
        default: '0.0.1'
        required: true
      is_latest:
        type: boolean
        description: Add "latest" tag
        default: true
      is_test:
        type: boolean
        description: Add "test" tag
      generate_extra:
        type: boolean
        description: Also generate "extra" images with more scripting options
        default: true
      add_gh_release:
        type: boolean
        description: Create GitHub release
        default: true

jobs:
  release_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Set tags
        id: set_tags
        run: |
          export ALL_TAGS="$TAG_NAME:${{ github.event.inputs.tagged_version }}"
          [ "${{ github.event.inputs.is_latest }}" = "true" ] && export ALL_TAGS="$ALL_TAGS,$TAG_NAME:latest"
          [ "${{ github.event.inputs.is_test }}" = "true" ] && export ALL_TAGS="$ALL_TAGS,$TAG_NAME:test"
          echo "all-tags=$ALL_TAGS" >> $GITHUB_OUTPUT

          export ALL_TAGS_EXTRA="$TAG_NAME_EXTRA:${{ github.event.inputs.tagged_version }}"
          [ "${{ github.event.inputs.is_latest }}" = "true" ] && export ALL_TAGS_EXTRA="$ALL_TAGS_EXTRA,$TAG_NAME_EXTRA:latest"
          [ "${{ github.event.inputs.is_test }}" = "true" ] && export ALL_TAGS_EXTRA="$ALL_TAGS_EXTRA,$TAG_NAME_EXTRA:test"
          echo "all-tags-extra=$ALL_TAGS_EXTRA" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ github.event.inputs.target_platforms }}
          push: true
          tags: ${{ steps.set_tags.outputs.all-tags }}
          provenance: false
          build-args: |
            DOTNET_SDK_PLATFORM=-amd64
            CRONCH_VERSION=${{ github.event.inputs.tagged_version }}
          outputs: type=image,name=${{ env.TAG_NAME }},annotation-index.org.opencontainers.image.source=https://github.com/indubitable/cronch,annotation-index.org.opencontainers.image.description=https://github.com/indubitable/cronch/releases/tag/${{ github.event.inputs.tagged_version }},annotation-index.org.opencontainers.image.licenses=BSD-2-Clause

      - name: Build and push (extra)
        uses: docker/build-push-action@v5
        if: ${{ github.event.inputs.generate_extra == 'true' }}
        with:
          context: .
          file: Dockerfile.extra
          platforms: ${{ github.event.inputs.target_platforms }}
          push: true
          tags: ${{ steps.set_tags.outputs.all-tags-extra }}
          provenance: false
          build-args: |
            DOTNET_SDK_PLATFORM=-amd64
            CRONCH_VERSION=${{ github.event.inputs.tagged_version }}
          outputs: type=image,name=${{ env.TAG_NAME_EXTRA }},annotation-index.org.opencontainers.image.source=https://github.com/indubitable/cronch,annotation-index.org.opencontainers.image.description=https://github.com/indubitable/cronch/releases/tag/${{ github.event.inputs.tagged_version }},annotation-index.org.opencontainers.image.licenses=BSD-2-Clause

      - uses: ncipollo/release-action@v1
        if: ${{ github.event.inputs.add_gh_release == 'true' }}
        with:
          commit: ${{ github.sha }}
          tag: ${{ github.event.inputs.tagged_version }}
          allowUpdates: true
          body: |
            Container images for this release are located at https://github.com/orgs/indubitable/packages?repo_name=cronch
